version: '3'
services:
  php-fpm:
    container_name: phpfpm      
    build: ./php/
    tty: true
    ports:
      - 9000:9000
    networks:
      - docker-network
    volumes:
      - ./api:/var/www/html/api
      - ./web:/var/www/html/web
  nginx:
    container_name: nginx
    build: ./nginx/
    tty: true
    ports:
      - 8080:80
      - 9443:443
    links:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.crt:/etc/nginx/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/nginx.key
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./api:/var/www/html/api
      - ./web:/var/www/html/web
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
