FROM nginx:1.21.4
MAINTAINER Jérôme LESAULNIER(jlesaulnier@yahoo.fr)

LABEL version="1.0"
LABEL description="API Gateway for peoplesphere coding game"
LABEL mail="jlesaulnier@yahoo.fr"

EXPOSE 443

ENTRYPOINT ["nginx","-g", "daemon off;"]

